### ISSUE TITLE
Option and filter for sending test emails using POSTMARK_API_TEST key

### ISSUE THREAD

**Issue by pderksen** [wildbit/postmark-wordpress#10]
From #6 via @atheken:

> You might also use our "testing" key for sending from staging, POSTMARK_API_TEST, as outlined here: http://developer.postmarkapp.com/developer-send-api.html

I'd love to see this added as an option (to toggle in plugin settings) and filter (to toggle programmatically). If I can view the emails within the Postmark dashboard without them getting actually sent, then this would 
alleviate the need to use Mailtrap or similar services for my staging site email testing.

**Comment by atheken** [comment]
@pderksen I'm not really sure it makes sense for this to be built in to the WP plugin.

If you'd like to verify that messages are processed by Postmark but want to "trap" them, then a really simple solution is to create a "Testing Trap" Inbound Server in Postmark, and send all of your test messages to the inbound address we provide for that server.

**Comment by planetahuevo** [comment]
I would like to see this. 
The reason for this feature is for the staging sites of WordPress.
you do not want to test emails, but to prevent them to reach users or clients from a staging site by mistake. 
Being able to activate this using an wp-config variable will make staging management of the emails much easier. 
On my example and your suggestion: you cannot send them to your inbox, because the emails are sent to your users  because this is a staging site, not a development one.

**Comment by pgraham3** [comment]
@planetahuevo You can now use **POSTMARK_API_TEST** for your API token in the plugin settings with v1.11.5 (just released). Emails won't be delivered but you can see the processing result in the Logs tab (make sure logging is enabled).
